# Generated by Django 3.1.2 on 2021-01-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210126_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='gallery'),
        ),
    ]
